--CATEGORY Table
CREATE TABLE CATEGORY(
  CATEGORYID	[int] IDENTITY(1,1) not null,
  CATEGORYNAME varchar(100),
  PARENTCATEGORYID int,
  ISDELETED bit not null,
  CREATEDDATE datetime not null,
  CREATORUSERID int not null,
  CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED
(
	[CATEGORYID] ASC
)WITH (PAD_INDEX = OFF,
STATISTICS_NORECOMPUTE = OFF,
IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
;
--PRODUCT Table
CREATE TABLE PRODUCT(
  PRODUCTID	[int] IDENTITY(1,1) not null,
  PRODUCNAME varchar(100),
  CATEGORYID int,
  PRICE money,
  IMAGEPATH varchar(250),
  ISDELETED bit not null,
  CREATEDDATE datetime not null,
  CREATORUSERID int not null,
  CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED
(
	[PRODUCTID] ASC
)WITH (PAD_INDEX = OFF,
STATISTICS_NORECOMPUTE = OFF,
IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
;
--PRODUCTPROPERTY Table
CREATE TABLE PRODUCTPROPERTY(
  PRODUCTPROPERTYID	[int] IDENTITY(1,1) not null,
  PRODUCTID int,
  PROPERTYID int,
  CONSTRAINT [PK_PRODUCTPROPERTY] PRIMARY KEY CLUSTERED
(
	[PRODUCTPROPERTYID] ASC
)WITH (PAD_INDEX = OFF,
STATISTICS_NORECOMPUTE = OFF,
IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
;
--PROPERTY Table
CREATE TABLE PROPERTY(
  PROPERTYID	[int] IDENTITY(1,1) not null,
  KEY_ varchar(100),
  VALUE varchar(100),
  CONSTRAINT [PK_PROPERTY] PRIMARY KEY CLUSTERED
(
	[PROPERTYID] ASC
)WITH (PAD_INDEX = OFF,
STATISTICS_NORECOMPUTE = OFF,
IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
;
--USER Table
CREATE TABLE USER_(
  USERID	[int] IDENTITY(1,1) not null,
  NAME varchar(100),
  SURNAME varchar(100),
  USERNAME varchar(100),
  HASHPASSWORD varchar(100),
  SALTPASSWORD varchar(100),
  CONSTRAINT [PK_USER_] PRIMARY KEY CLUSTERED
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF,
STATISTICS_NORECOMPUTE = OFF,
IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
;

/*AÇIKLAMA*/
/*
1-PROPERTY tablosunda KEY kolonunun KEY_ olarak tanımlamak zorunda kaldım.
2-USER tablosunu USER_ tanımlamak zorunda kaldım.
3-Foreign key'i özellikle oluşturmadım. Çünkü Foreign Key DB de yavaşlığa sebebiyet veriyor.Bu tarzlı işlemleri validasyon içersinde kontrol ediyorum.
*/